### PR TITLE
Allow generation of dynamic graphs

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
Uses the dynamic queries functions to allow the generation of dynamic graphs.
Addresses #8

### CODE REVIEW

**Comment by mathias-baumann-sociomantic** [comment]
Update:
- html() method seems to leak memory, using document... to re-generate graphs upon update
- rebased upon latest master

**Comment by mathias-baumann-sociomantic** [comment]
Update:
- Sort the generated graphs

**Comment by mathias-baumann-sociomantic** [comment]
ping?

**Comment by berniecamus** [comment]
Sorry, have I missed a message? I'm actually in Spain heading to Russia at
the moment so have bad communication

**Comment by mathias-baumann-sociomantic** [comment]
Well, I thought I Ping this PR which is open since 2013 and no response from the maintainer ;)

**Comment by berniecamus** [comment]
Ah thanks! :) please do close if you want. You resolved my issue then.

**Comment by mathias-baumann-sociomantic** [comment]
I am confused.. so you don't want the feature?

**Comment by berniecamus** [comment]
Sorry, I'm also confused: I only contacted you once, and your resolved my
issue at the time. I haven't worked on that product for years, so there is
nothing required for me.

Do you need me to close something this side?

Thanks,
Bernie

**Comment by mathias-baumann-sociomantic** [comment]
My goals is getting this PR merged. I assumed you're the maintainer that can make that happen because you responded ;)

**Comment by berniecamus** [comment]
Ah no, I have no idea even what you're actually asking, and am not involved
with graphite, graphatitus, or even with computers at the present time.

**Comment by mathias-baumann-sociomantic** [comment]
In that case... you don't need to do anything ;)

**Comment by mathias-baumann-sociomantic** [comment]
@ezbz ping

**Comment by mathias-baumann-sociomantic** [comment]
Alright, I guess the repo owner doesn't care anymore, so I am closing this

**Pull request closed without merging**
